version: "3"
services:
  mock-backend:
    build: 
      context: .
      dockerfile: dockerfile.lab
    container_name: mock-backend
    ports:
      - "5000:5000"
    volumes:
      - ./src:/root/src
    command: "python main.py"